apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
    - name: nodewebapp
      image: vishuddhasamarasekara/calculator-image:1.0
      ports:
        - containerPort: 3040
